# Example configuration for gphotos-321sync-takeout-extractor
# Copy this file to:
#   Windows: %LOCALAPPDATA%\gphotos-321sync-takeout-extractor\config.toml
#   Linux:   ~/.config/gphotos-321sync-takeout-extractor/config.toml
#   Mac:     ~/Library/Application Support/gphotos-321sync-takeout-extractor/config.toml

[extraction]
source_dir = "G:\\My Drive\\Takeout"
target_media_path = "C:\\Users\\papav\\takeout_tests"

# Optional: Logging configuration
[logging]
level = "INFO"              # DEBUG, INFO, WARNING, ERROR
format = "json"             # simple, detailed, json
# file = "C:\\Users\\papav\\logs\\extractor.log"  # Optional: log to file
