# Default configuration for gphotos-sync
# This file is shipped with the application and should not be modified by users
# User overrides should go in user config file or environment variables

[app]
name = "gphotos-sync"
version = "0.1.0"

[deployment]
mode = "local"  # local | hybrid | cloud_only
environment = "production"  # production | development | testing

[paths]
# Variables: ${USER_HOME}, ${USER_DATA}, ${USER_CONFIG}, ${USER_CACHE}, ${USER_LOGS}, ${TEMP}
takeout_archives = "${USER_HOME}/Downloads"
working_directory = "${USER_DATA}/gphotos-sync"
database_path = "${USER_DATA}/gphotos-sync/metadata.db"
config_directory = "${USER_CONFIG}/gphotos-sync"
log_directory = "${USER_LOGS}/gphotos-sync"
cache_directory = "${USER_CACHE}/gphotos-sync"
temp_directory = "${TEMP}/gphotos-sync"

[resources]
# CPU
max_cpu_percent = 70.0
max_workers = 0  # 0 = auto-detect (cpu_count - 2)
io_workers = 0   # 0 = auto-detect (cpu_count * 3)

# Memory
max_memory_percent = 50.0
max_memory_mb = 0  # 0 = no hard limit, use percentage only

# Disk I/O
max_concurrent_reads = 10
max_disk_io_mbps = 100.0

# Monitoring
resource_check_interval_seconds = 5.0
enable_adaptive_throttling = true

[processing]
batch_size = 1000
chunk_size = 100
enable_parallel_processing = true
backup_originals = true
verify_integrity = true

[extraction]
extract_to_temp = true
cleanup_after_extraction = false
verify_checksums = true
supported_formats = ["zip", "tar", "tar.gz", "tar.bz2", "7z", "rar"]

[metadata]
conflict_resolution = "google_json_priority"  # google_json_priority | exif_priority | manual
embed_gps = true
embed_timestamps = true
embed_camera_info = true
preserve_original_dates = true
supported_image_formats = ["jpg", "jpeg", "png", "gif", "bmp", "webp", "heic", "heif", "tiff", "raw", "cr2", "nef", "arw"]
supported_video_formats = ["mp4", "mov", "avi", "mkv", "webm", "m4v", "3gp"]

[database]
type = "sqlite"  # sqlite | postgresql
connection_pool_size = 5
connection_timeout_seconds = 30.0
enable_wal_mode = true
backup_enabled = true
backup_interval_hours = 24

[database.sqlite]
journal_mode = "WAL"
synchronous = "NORMAL"
cache_size_kb = 10000

[database.postgresql]
host = ""
port = 5432
database = ""
username = ""
password = ""
ssl_mode = "require"
pool_size = 10
max_overflow = 20

[api]
host = "127.0.0.1"
port = 8080
reload = false
workers = 1
enable_cors = false
cors_origins = []
enable_compression = true
max_upload_size_mb = 5000

[api.websocket]
ping_interval_seconds = 30.0
ping_timeout_seconds = 10.0
max_connections = 100

[storage]
provider = "local"  # local | s3 | gcs | azure
enable_encryption = false

[storage.s3]
bucket = ""
region = "us-east-1"
access_key_id = ""
secret_access_key = ""
endpoint_url = ""
use_ssl = true

[storage.gcs]
bucket = ""
project_id = ""
credentials_file = ""

[queue]
backend = "none"  # none | redis | sqs | rabbitmq
result_backend = "none"

[queue.redis]
host = "localhost"
port = 6379
db = 0
password = ""
ssl = false

[queue.sqs]
region = "us-east-1"
queue_url = ""
access_key_id = ""
secret_access_key = ""

[logging]
level = "INFO"  # DEBUG | INFO | WARNING | ERROR | CRITICAL
format = "detailed"  # simple | detailed | json
enable_file_logging = true
enable_console_logging = true
max_file_size_mb = 10
backup_count = 5
log_to_syslog = false

[monitoring]
enable_performance_tracking = true
enable_profiling = false
profile_threshold_seconds = 5.0
metrics_export_interval_seconds = 60.0

[ui]
theme = "auto"  # light | dark | auto
language = "en"
enable_animations = true
items_per_page = 50

[gallery]
thumbnail_size = 200
thumbnail_quality = 85
enable_lazy_loading = true
group_by = "year"  # year | month | day | album

[security]
enable_authentication = false
session_timeout_minutes = 60
enable_rate_limiting = false
rate_limit_requests_per_minute = 100

[features]
enable_face_detection = false
enable_duplicate_detection = true
enable_auto_tagging = false
enable_cloud_sync = false
enable_sharing = false

[development]
enable_debug_mode = false
enable_hot_reload = false
mock_external_services = false
